# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'is_lunch_map' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for is_lunch_map
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'
  pod 'ObjectMapper'
  pod 'SnapKit'
  pod 'AlamofireImage'

  target 'is_lunch_mapTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking'
    pod 'RxTest'
  end

  target 'is_lunch_mapUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
